"""add require_selfie to user_settings

Revision ID: b9e4c09496a1
Revises: 00e3759d911c
Create Date: 2026-05-23 01:15:18.142509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9e4c09496a1'
down_revision: Union[str, None] = '00e3759d911c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('require_selfie', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'require_selfie')
    # ### end Alembic commands ###
